### ISSUE TITLE
Can't Install on HassOS 1.7

### ISSUE THREAD

**Issue by hugodelaroza** [keatontaylor/hassio-addons#3]
Hi, I'm trying to install the api in HassOS 1.7 and I recive the following error:

18-07-16 21:34:27 INFO (SyncWorker_19) [hassio.docker.interface] Pull image keatontaylor/aarch64-addon-alexa-api tag 0.5.
18-07-16 21:34:30 ERROR (SyncWorker_19) [hassio.docker.interface] Can't install keatontaylor/aarch64-addon-alexa-api:0.5 -> 404 Client Error: Not Found ("pull access denied for keatontaylor/aarch64-addon-alexa-api, repository does not exist or may require 'docker login'").

Can somebody help me?

Thanks!!

**Comment by keatontaylor** [comment]
aarch64 is the 64-bit architecture for ARM based devices like the raspberry pi. Unfortunately, I haven't compiled the add-on to work on that system. It was part of the process but my focus has changed to make the component no longer require the add-on and be platform independent. So stay tuned.

**Comment by hugodelaroza** [comment]
If I change my os to 32 bit will ir work?
